### ISSUE TITLE
Create docker image for horta deployment

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-docker-images#12]
As an devops engineer, I want an easy and consistent way to deploy hortacloud.

- [x] Add a folder to this repo hortacloud-deployment that contains
- [x] A Readme file with instructions on how to deploy hortacloud via 
- [x] A Dockerfile
- [x] The Dockerfile should be based on node16 and have commands to install aws cli and cdk
- [ ] (Optional?) Publish the docker image

**Comment by yosefmaru** [comment]
Task duration: This ticket took a little longer than expected.
